### ISSUE TITLE
Implement get_all_stops wrapper method

### ISSUE THREAD

**Issue by axelniklasson** [axelniklasson/vasttrafik-api-wrapper#1]
Can't seem to get this one to work and when I try it out in Västtrafik's API console, I get no data there either. Perhaps a backend issue? Anyway, I get a 403 Unauthorized when I try to fetch data from that endpoint. No idea.

**Comment by erikkinding** [comment]
Even though this was marked as wontfix, I'll give it a shot. I think you might have experienced issues with the API itself during previous attempts. I've been in contact with Västtrafik regarding other parts of the API that behaved strangely, and they seem to be very enthusiastic about taking care of any reported issue.

**Comment by axelniklasson** [comment]
@erikkinding That sounds like a great idea! Would be awesome to have it fixed 👍
