### ISSUE TITLE
Better handling of API keys

### ISSUE THREAD

**Issue by erikkinding** [axelniklasson/vasttrafik-api-wrapper#10]
It would be nice to have a more convenient way of handling the consumer key and secret. A suggestion is to pass these values in the constructor of Client.

Maybe add some handy functionality to demo.py to fetch keys from a file covered by .gitignore?

**Comment by axelniklasson** [comment]
@erikkinding I merged some code from the development branch yesterday, where this is fixed. Check client.py @ line 25, where you can send key and secret as arguments to the constructor :)

**Comment by erikkinding** [comment]
Nice!
